Add many additions to CI testing. Please take a look.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -28,10 +28,17 @@ jobs:
         run: |
           ls /.dockerenv && echo Found dockerenv
           echo "No dockerenv"
-          python --version || echo "Python not found!"
+          python3 --version || echo "Python not found!"
       - name: Compile example/vgg
         run: |
-          cd examples/vgg && chpl test.chpl -M ../../src -M ../../lib -o vgg
+          cd examples/vgg 
+            && chpl test.chpl -M ../../src -M ../../lib -o vgg 
+            && python3 dump_weights.py
+            && python3 process_img.py imgs/frog.jpg
+            && ./vgg imgs/frog.chdata
+      - name: Run correspondence tests
+        run: |
+          (cd test/correspondence && python3 correspondence.py) || echo "Wups! Correspondence bug or more likely test failure!"
       - name:
         run: |
           echo "Pau!"
